services:
  backend:
    restart: always
    env_file: .env
    build: ./backend
    ports:
      - ${PORT}:${PORT}
    environment:
      PORT: ${PORT}
      DB_HOST: mysql
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      WAIT_HOSTS: mysql:3306
      WAIT_TIMEOUT: 600
      WAIT_SLEEP_INTERVAL: 10
    links:
      - mysql
    depends_on:
      - mysql
    command: sh -c "/wait && npm run server"
    volumes:
      - ./backend:/usr/src/backend
      - ./backend/node_modules:/usr/src/backend/node_modules
  mysql:
    image: mysql
    restart: always
    env_file: .env
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
