services:
  backend:
    restart: always
    env_file: ".env"
    build: .
    ports:
      - "${LOCAL_PORT}:${LOCAL_PORT}"
    environment:
      DB_HOST: "mysql"
      LOCAL_PORT: "${LOCAL_PORT}"
      DB_PORT: "${DB_PORT}"
      DB_DATABASE: "${DB_DATABASE}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      WAIT_HOSTS: mysql:3306
      WAIT_TIMEOUT: 60
      WAIT_SLEEP_INTERVAL: 10
    depends_on:
      - mysql
    command: sh -c "/wait && node server.js"
  mysql:
    image: "mysql"
    restart: always
    env_file: ".env"
    ports:
      - "3306:3306"
    expose:
      - 3306
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
