name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    environment: docker-node-crud

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose up --build
