name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PORT: ${{ secrets.PORT }}
  DB_PORT: ${{ secrets.DB_PORT }}
  DB_DATABASE: ${{ secrets.DB_DATABASE }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  
jobs:

  build:

    runs-on: ubuntu-latest
    environment: docker-node-crud

    steps:
    - name: Create env file - Root
      run: |
        touch .env
        echo PORT=${{ secrets.PORT }} >> .env
        echo DB_PORT=${{ secrets.secrets.DB_PORT }} >> .env
        echo DB_DATABASE=${{ secrets.secrets.DB_DATABASE }} >> .env
        echo DB_USER=${{ secrets.secrets.DB_USER }} >> .env
        echo DB_PASSWORD=${{ secrets.secrets.DB_PASSWORD }} >> .env
        cat .env
        
    - name: Create env file - Backend
      run: |
        touch backend/.env
        echo PORT=${{ secrets.PORT }} >> .env
        echo DB_PORT=${{ secrets.secrets.DB_PORT }} >> .env
        echo DB_DATABASE=${{ secrets.secrets.DB_DATABASE }} >> .env
        echo DB_USER=${{ secrets.secrets.DB_USER }} >> .env
        echo DB_PASSWORD=${{ secrets.secrets.DB_PASSWORD }} >> .env
        cat .env
          
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose up --build
